Repository alois9866/lexibot, pull requests merged in 2021-04, with the labels that each got.

#9 Add server API
  README.md
  docs/api_description.md
  server/application.py
  server/main.py
  server/model.py
  server/tf/main.tf
  server/tf/scripts/create.sql
Labels: feature

#10 Add unit tests for model
  Makefile
  requirements.txt
  server/model.py
  server/test_model.py
  server/tf/main.tf
Labels: feature

#11 Update bot interactive logic
  .gitignore
  .pylintrc
  Makefile
  bot/parser.py
  bot/telegram_bot.py
  bot/test_parser.py
  requirements.txt
Labels: feature

#12 Remove unnecessary pylint warning removals
  .pylintrc
Labels: improvement

#13 Update project description. Integrate sphinx documentation generator.
  Makefile
  README.md
  bot/telegram_bot.py
  docs/doc_build/doctrees/BotClientApi.doctree
  docs/doc_build/doctrees/ServerApi.doctree
  docs/doc_build/doctrees/environment.pickle
  docs/doc_build/doctrees/index.doctree
  docs/doc_build/html/.buildinfo
  docs/doc_build/html/BotClientApi.html
  docs/doc_build/html/ServerApi.html
  docs/doc_build/html/_sources/BotClientApi.rst.txt
  docs/doc_build/html/_sources/ServerApi.rst.txt
  docs/doc_build/html/_sources/index.rst.txt
  docs/doc_build/html/_static/basic.css
  docs/doc_build/html/_static/classic.css
  docs/doc_build/html/_static/doctools.js
  docs/doc_build/html/_static/documentation_options.js
  docs/doc_build/html/_static/file.png
  docs/doc_build/html/_static/jquery-3.5.1.js
  docs/doc_build/html/_static/jquery.js
  docs/doc_build/html/_static/language_data.js
  docs/doc_build/html/_static/minus.png
  docs/doc_build/html/_static/plus.png
  docs/doc_build/html/_static/pygments.css
  docs/doc_build/html/_static/searchtools.js
  docs/doc_build/html/_static/sidebar.js
  docs/doc_build/html/_static/underscore-1.12.0.js
  docs/doc_build/html/_static/underscore.js
  docs/doc_build/html/genindex.html
  docs/doc_build/html/index.html
  docs/doc_build/html/objects.inv
  docs/doc_build/html/py-modindex.html
  docs/doc_build/html/search.html
  docs/doc_build/html/searchindex.js
  docs/make.bat
  docs/source/BotClientApi.rst
  docs/source/ServerApi.rst
  docs/source/conf.py
  docs/source/index.rst
  requirements.txt
  server/application.py
Labels: documentation

#14 Update bot logic. Refactor input interface.
  .gitignore
  .pylintrc
  Makefile
  README.md
  bot/config.json
  bot/main.py
  bot/telegram_bot.py
  docs/doc_build/doctrees/BotClientApi.doctree
  docs/doc_build/doctrees/environment.pickle
  docs/doc_build/html/BotClientApi.html
  docs/doc_build/html/genindex.html
  docs/doc_build/html/objects.inv
  docs/doc_build/html/searchindex.js
  server/application.py
  server/main.py
  server/model.py
  utils/logging.py
Labels: improvement

#17 Add localization
  .gitignore
  .pylintrc
  Makefile
  README.md
  bot/main.py
  bot/telegram_bot.py
  docs/doc_build/doctrees/BotClientApi.doctree
  docs/doc_build/doctrees/environment.pickle
  docs/doc_build/doctrees/index.doctree
  docs/doc_build/html/BotClientApi.html
  docs/doc_build/html/_sources/index.rst.txt
  docs/doc_build/html/genindex.html
  docs/doc_build/html/index.html
  docs/doc_build/html/objects.inv
  docs/doc_build/html/searchindex.js
  docs/source/index.rst
  l10n/lexibot.pot
  l10n/ru/LC_MESSAGES/lexibot.po
  requirements.txt
  server/application.py
  server/main.py
  utils/logging.py
Labels: feature

#18 Fix linting
  Makefile
  bot/main.py
  bot/parser.py
  bot/telegram_bot.py
  docs/doc_build/doctrees/BotClientApi.doctree
  docs/doc_build/doctrees/ServerApi.doctree
  docs/doc_build/doctrees/environment.pickle
  docs/doc_build/doctrees/index.doctree
  docs/doc_build/html/BotClientApi.html
  docs/doc_build/html/ServerApi.html
  docs/doc_build/html/index.html
  docs/doc_build/html/searchindex.js
  l10n/ru/LC_MESSAGES/lexibot.po
  requirements.txt
  server/application.py
  server/model.py
Labels: bug
